### PR TITLE
Replace sqwish with clean-css.

### LINKED ISSUE #174: Consider clean-css as the default CSS minifier to replace sqwish
[sqwish](https://github.com/ded/sqwish) is no longer maintained.  [clean-css](https://github.com/jakubpawlowicz/clean-css) is actively maintained.

### PR DESCRIPTION
**Pull request by austinkelleher**
Fixes https://github.com/lasso-js/lasso/issues/174

### CODE REVIEW

**Comment by yomed** [comment]
FYI I have been using https://github.com/yomed/lasso-clean-css for a while. @patrick-steele-idem Should I deprecate my plugin in favor of this one?

**Comment by patrick-steele-idem** [comment]
/cc @mlrawlings @philidem 

Good question @yomed.  Here are some thoughts:
- I don't like that lasso ships with a not-so-great and unmaintained CSS minifier
- Do we want to document that the builtin CSS minifier uses `clean-css` or do we want to hide that as an implementation detail?
- If document lasso as using `clean-css` then we can just point to the docs for `clean-css` but we would never be able to change the implementation in the future without risking breaking things
- If we hide the fact that the builtin CSS minifier uses `clean-css` then we would want to control which plugin options are allowed and document them very clearly

Maybe provide a builtin CSS minifier that only provides a few options that we control, but also promote `lasso-clean-css` that allows for the developer to harness the full power of `clean-css`?

Thoughts?

**Comment by patrick-steele-idem** [comment]
On a related note, we should probably consider updating the core CSS dependency handler to support including `@import` dependencies found in the CSS source code and commenting those `@import` lines out

**Comment by yomed** [comment]
> Maybe provide a builtin CSS minifier that only provides a few options that we control, but also promote lasso-clean-css that allows for the developer to harness the full power of clean-css?

I think that makes sense, and it does seem like that was a benefit of using a no-frills minifier like `sqwish` by default. But if you were to replace it with `clean-css`, it seems strange to explicitly limit its usefulness by disallowing custom config.

**Comment by austinkelleher** [comment]
I think this brings up a good issue. This is also applicable to other lasso plugins like `lasso-minify-js`. I think it's better to keep the minifier dependencies in the core plugins as implementation details in case we chose to change it later, but there are definitely benefits to having dependency specific plugins such as `lasso-clean-css`. I would support having a clear and well-documented list of options that the API supports in core plugins. If we choose to switch dependencies in the core plugins, we could add/deprecate the supported options accordingly. This also gives us more control on exactly what we want these properties to be named.

**Pull request closed without merging**
